repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.2
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, jupyter ]
  - repo: local
    hooks:
      - id: sync_doc_requirements
        name: sync_doc_requirements
        entry: poetry export --with doc --without-hashes -o docs/requirements.txt -f requirements.txt
        language: system
        pass_filenames: false
        files: 'poetry.lock'
