repos:
  - repo: local
    hooks:

      - id: black
        name: black
        language: system
        entry: black
        types: [ python ]

      - id: flake8
        name: flake8
        language: system
        entry: flake8
        types: [ python ]

  - repo: https://github.com/python-poetry/poetry
    rev: ''
    hooks:
      - id: poetry-check
        name: Poetry check

      - id: poetry-export
        name: Sync doc requirements
        args: [ "--dev", "--without-hashes", "-f", "requirements.txt", "-o", "docs/requirements.txt" ]
